SET LINESIZE 500
SET PAGESIZE 50
SET FEEDBACK ON

COLUMN paymentdigits HEADING 'Digits' FORMAT A6
COLUMN paymentcompany HEADING 'Company' FORMAT A15
COLUMN paymenttype HEADING 'Type' FORMAT A6
COLUMN paymentID HEADING 'Payment|ID' FORMAT 9999999

COLUMN customerID HEADING 'Customer|ID' FORMAT 999,999
COLUMN fName HEADING 'First|Name' FORMAT A10
COLUMN mName HEADING 'Middle|Name' FORMAT A11
COLUMN lName HEADING 'Last|Name' FORMAT A11
COLUMN phone HEADING 'Phone' FORMAT 9999999999
COLUMN email HEADING 'Email' FORMAT A22
COLUMN street HEADING 'Street' FORMAT A18
COLUMN city HEADING 'City' FORMAT A15
COLUMN State HEADING 'State' FORMAT A5
COLUMN zip HEADING 'Zip' FORMAT A5

COLUMN OrderID HEADING 'Order|ID' FORMAT 9,999
COLUMN shippingCost HEADING 'Shipping|Cost' FORMAT $9,999.99
COLUMN ORDERTIMEstamp HEADING 'Timestamp' FORMAT A16
COLUMN zip HEADING 'Zip' FORMAT A5

COLUMN productID HEADING 'Product|ID' FORMAT A7
COLUMN Quantity HEADING 'Quantity' FORMAT 9999999

COLUMN trackingNo HEADING 'Tracking|Number' FORMAT 99999999
COLUMN Shippingcompany HEADING 'Shipping|Company' FORMAT A8

COLUMN ShoesID HEADING 'Shoes|ID' FORMAT 9999
COLUMN usSize HEADING 'US|Size' FORMAT 9999
COLUMN euSize HEADING 'EU|Size' FORMAT 9999
COLUMN TopID HEADING 'Top|ID' FORMAT 9999
COLUMN TopFit HEADING 'Top Fit' FORMAT A8
COLUMN TopSize HEADING 'Top|Size' FORMAT A4
COLUMN TopType HEADING 'Top Type' FORMAT A12
COLUMN bottomID HEADING 'Bottom|ID' FORMAT 9999
COLUMN bottomFit HEADING 'Bottom|Fit' FORMAT A8
COLUMN bottomSize HEADING 'Bottom|Size' FORMAT A6
COLUMN bottomType HEADING 'Bottom|Type' FORMAT A12

COLUMN productID HEADING 'Product|ID' FORMAT 9999
COLUMN productName HEADING 'Product Name' FORMAT A27
COLUMN productDescription HEADING 'Description' FORMAT A25
COLUMN productQuantity HEADING 'Quantity' FORMAT 999,999
COLUMN productPrice HEADING 'Price' FORMAT $9,999.99
COLUMN productSection HEADING 'Section' FORMAT A7
COLUMN ProductColor HEADING 'Color' FORMAT A12
COLUMN productCollection HEADING 'Collection' FORMAT A12
COLUMN productCategory HEADING 'Category' FORMAT A18
COLUMN discount HEADING 'Discount' FORMAT $99,999.99


COLUMN Subtotal HEADING 'Subtotal' FORMAT $9,999.99
COLUMN Shipping HEADING 'Shipping|Cost' FORMAT $9,999.99
COLUMN Tax HEADING 'Tax' FORMAT $9,999.99
COLUMN "Total Discount" FORMAT $9,999.99
